<?php
declare(strict_types=1);
require_once __DIR__ . '/functions.php';
start_secure_session();
if (!empty($_SESSION['logged_in']) && !empty($_SESSION['user_id'])) { header('Location: profile.php?id=' . (int)$_SESSION['user_id']); exit; }
if (empty($_SESSION['captcha_verified_until']) || (int)$_SESSION['captcha_verified_until'] < time()) { header('Location: index.php'); exit; }
$csrf=csrf_token();
?><!DOCTYPE html><html lang="ru"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Регистрация</title><link rel="icon" href="favicon.ico" type="image/x-icon"><link rel="stylesheet" href="css/style_reg.css"></head><body><main class="card"><h1>Создать аккаунт</h1><p class="subtitle">Заполните поля для регистрации</p><div class="server-error" id="serverError" role="alert"></div><div class="server-success" id="serverSuccess" role="status"></div><form id="registerForm" novalidate method="POST" action="registration.php"><input type="hidden" name="csrf_token" value="<?= htmlspecialchars($csrf,ENT_QUOTES,'UTF-8') ?>"><div class="field"><label for="user">Имя пользователя</label><input type="text" id="user" name="user" maxlength="100" required><div class="error" id="userError"></div></div><div class="field"><label for="userLogin">Логин</label><input type="text" id="userLogin" name="userLogin" maxlength="30" required><div class="error" id="userLoginError"></div></div><div class="field"><label for="password">Пароль</label><input type="password" id="password" name="password" minlength="8" required><div class="error" id="passwordError"></div></div><button type="submit" id="submitBtn">Зарегистрироваться</button></form><p class="subtitle"><a href="index.php">На главную</a></p></main><script>
(()=>{const f=document.getElementById('registerForm'),e=document.getElementById('serverError'),ok=document.getElementById('serverSuccess'),b=document.getElementById('submitBtn');function er(id,m){const i=document.getElementById(id),x=document.getElementById(id+'Error');i.classList.toggle('invalid',!!m);x.textContent=m||'';}f.addEventListener('submit',async ev=>{ev.preventDefault();e.style.display='none';ok.style.display='none';let v=true;const u=document.getElementById('user').value.trim(),l=document.getElementById('userLogin').value.trim(),p=document.getElementById('password').value;er('user','');er('userLogin','');er('password','');if(!u){er('user','Введите имя пользователя.');v=false;}if(!/^[A-Za-z0-9_]{3,30}$/.test(l)){er('userLogin','Введите корректный логин.');v=false;}if(p.length<8){er('password','Минимум 8 символов.');v=false;}if(!v)return;b.disabled=true;try{const r=await fetch(f.action,{method:'POST',body:new FormData(f),credentials:'same-origin',headers:{Accept:'application/json'}}),d=await r.json();if(!r.ok)throw new Error(d.error||'Ошибка регистрации.');ok.textContent=d.message||'Регистрация завершена.';ok.style.display='block';f.reset();setTimeout(()=>location.href='index.php',1200);}catch(x){e.textContent=x.message;e.style.display='block';}finally{b.disabled=false;}})})();
</script></body></html>